// Generated by scripts/util/generate-types-from-spec.ts
// DO NOT EDIT THIS FILE DIRECTLY
// Service: AWS::XRay

export interface Tag {
  /** The value for the tag. You can specify a value that's 1 to 256 characters in length. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. */
  Value: string;
  /** The key name of the tag. You can specify a value that's 1 to 128 Unicode characters in length and can't be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., :, /, =, +, @, -, and ". */
  Key: string;
}

export interface InsightsConfiguration {
  /** Set the NotificationsEnabled value to true to enable insights notifications. Notifications can only be enabled on a group with InsightsEnabled set to true. */
  NotificationsEnabled?: boolean;
  /** Set the InsightsEnabled value to true to enable insights or false to disable insights. */
  InsightsEnabled?: boolean;
}

export interface SamplingRule {
  /** The priority of the sampling rule. */
  Priority: number;
  /** A fixed number of matching requests to instrument per second, prior to applying the fixed rate. The reservoir is not used directly by services, but applies to all services using the rule collectively. */
  ReservoirSize: number;
  /** The ARN of the sampling rule. Specify a rule by either name or ARN, but not both. Specifying a sampling rule by name is recommended, as specifying by ARN will be deprecated in future. */
  RuleARN?: string;
  /** Matches the path from a request URL. */
  URLPath: string;
  /** Matches attributes derived from the request. Maximum number of 5 items. Key Length Constraints: Minimum length of 1. Maximum length of 32. Value Length Constraints: Minimum length of 1. Maximum length of 32. @pattern ".{1,}" */
  Attributes?: Record<string, any>;
  /** The percentage of matching requests to instrument, after the reservoir is exhausted. */
  FixedRate: number;
  /** Matches the hostname from a request URL. */
  Host: string;
  /** Matches the ARN of the AWS resource on which the service runs. */
  ResourceARN: string;
  /** Matches the HTTP method of a request. */
  HTTPMethod: string;
  /** Matches the name that the service uses to identify itself in segments. */
  ServiceName: string;
  /** The version of the sampling rule. Version can only be set when creating a new sampling rule. */
  Version?: number;
  /** Matches the origin that the service uses to identify its type in segments. */
  ServiceType: string;
  /** The name of the sampling rule. Specify a rule by either name or ARN, but not both. */
  RuleName?: string;
}

/** http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-xray-group.html */
export interface GroupProps {
  /** The unique case-sensitive name of the group. @pattern "^[a-zA-Z0-9-_]{1,32}$" */
  GroupName: string;
  /** The structure containing configurations related to insights. */
  InsightsConfiguration?: InsightsConfiguration;
  /** The filter expression defining the parameters to include traces. */
  FilterExpression?: string;
  /** An array of key-value pairs to apply to this resource. */
  Tags?: Tag[];
}

export interface GroupOutput extends GroupProps {
  readonly GroupARN: string;
}

/** http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-xray-resourcepolicy.html */
export interface ResourcePolicyProps {
  /** A flag to indicate whether to bypass the resource-based policy lockout safety check. */
  BypassPolicyLockoutCheck?: boolean;
  /** The name of the resource-based policy. Must be unique within a specific AWS account. @pattern "[\w+=,.@-]+" */
  PolicyName: string;
  /** The resource-based policy document, which can be up to 5kb in size. */
  PolicyDocument: string;
}

export interface ResourcePolicyOutput extends ResourcePolicyProps {}

/** http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-xray-samplingrule.html */
export interface SamplingRuleProps {
  /** The sampling rule to be created or updated. */
  SamplingRule?: SamplingRule;
  /** An array of key-value pairs to apply to this resource. */
  Tags?: Tag[];
}

export interface SamplingRuleOutput extends SamplingRuleProps {
  readonly RuleARN: string;
}

/** http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-xray-transactionsearchconfig.html */
export interface TransactionSearchConfigProps {
  /** Specifies the percentage of requests to index. This value must be between 0 and 100. @pattern "^[0-9]{1,3}$" */
  IndexingPercentage?: number;
}

export interface TransactionSearchConfigOutput extends TransactionSearchConfigProps {
  readonly AccountId: string;
}

interface XRay {
  Group: (props: GroupProps) => GroupOutput;
  ResourcePolicy: (props: ResourcePolicyProps) => ResourcePolicyOutput;
  SamplingRule: (props: SamplingRuleProps) => SamplingRuleOutput;
  TransactionSearchConfig: (props: TransactionSearchConfigProps) => TransactionSearchConfigOutput;
}

export default XRay;
